name: Run unit-tests

on:
  push:
    branches:
      - master
      - spoonify
      - actions
  pull_request:
    branches:
      - master
      - spoonify
      - actions


jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Install apps
        uses: ConorMacBride/install-package@v1
        with:
          brew: bash
          brew-cask: hammerspoon
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Create hammerspoon paths
        run: |
          mkdir -p ~/.hammerspoon/Spoons/Spacehammer.spoon
      - name: Copy spoon to correct path
        run: |
          echo $GITHUB_WORKSPACE
          cp -R $GITHUB_WORKSPACE/* ~/.hammerspoon/Spoons/Spacehammer.spoon/
      - name: Start Hammerspoon
        run: open -a Hammerspoon
      - name: Run unit tests
        run: |
          cd ~/.hammerspoon/Spoons/Spacehammer.spoon/
          hs -c 'hs.ipc.cliInstall()'
          ./run-test ./spacehammer/test/*
