name: Run unit-tests

on:
  push:
    branches:
      - master
      - spoonify
      - actions
  pull_request:
    branches:
      - master
      - spoonify
      - actions


jobs:
  build:
    runs-on: macos-12
        # working-directory: /Users/runner/.hammerspoon/
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          brew: bash
          brew-cask: hammerspoon
      - uses: actions/checkout@v4
      - name: Create paths
        run: |
          mkdir -p ~/.hammerspoon/Spoons/Spacehammer.spoon
      - name: Copy to correct path
        run: |
          echo $GITHUB_WORKSPACE
          ls -l $GITHUB_WORKSPACE
          cp -R $GITHUB_WORKSPACE/* ~/.hammerspoon/Spoons/Spacehammer.spoon/
          ls -l ~/.hammerspoon/Spoons/Spacehammer.spoon/
      - name: Run tests
        run: |
          cd ~/.hammerspoon/Spoons/Spacehammer.spoon/
          ls -al
          ./run-test ./spacehammer/test/*
