name: Run unit-tests

on:
  push:
    branches:
      - master
      - spoonify
      - actions
  pull_request:
    branches:
      - master
      - spoonify
      - actions


jobs:
  build:
    runs-on: macos-12
    defaults:
      run:
        working-directory: ~/.hammerspoon/
    steps:
      - uses: actions/checkout@v2
      - uses: ConorMacBride/install-package@v1
        with:
          brew: bash
          brew-cask: hammerspoon
      - name: Run tests
        run: ./run-tests spacehammer/test/*
